Os ubuntu
Update apt repo
Install dependencies using apt
install python dependencies using pip
copy source code to /apt folder
Run the web server usinf flask command

From Ubuntu

RUN apt-get update
RUN apt-get install python

RUN pip install flask
RUN pip install flask-mysql

COPY ./apt/source-code

ENTRYPOINT FLASK_APP=/opt/source-code/app.py flask run

Build 
docker build dockerfile -t mmumshad/my-custom-app
